name: twitter_like
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sliding_up_panel: any
  intl: any
  auto_route: ^7.9.0
  google_fonts: 6.1.0
  sizer: ^2.0.15
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.0
  iconsax: ^0.0.8
  fluttersax: ^0.0.6
  unicons: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/home/
